apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: job-board-ingress
  namespace: job-board
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: job-board.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: job-board-api
                port:
                  number: 80
